### PR TITLE
fix deprecated: strtoupper(): Passing null to parameter (#144)

### PR DESCRIPTION
**Pull request by turbopixel**

### CODE REVIEW

**Comment by rdanklof** [comment]
I have the same issue after upgrading to PHP 8.1.1. It would be nice if this Pull Request can make it through 👍

**Comment by vojtabiberle** [comment]
Please merge :-)

**Comment by turbopixel** [comment]
@stephangroen @casperbakker

**Comment by stephangroen** [comment]
Thank you @turbopixel, sorry for the delay.

**Pull request merged**
