### PR TITLE
Added and executed PHP-CS-Fixer

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by casperbakker** [comment]
Hi @OskarStark,

I am sorry, but I do not agree with these style changes. What is the reason you think it needs to be changed?

**Comment by OskarStark** [comment]
Hi @casperbakker,

i like to use PSR standards, and the `@Symfony` rule from PHP-CS-Fixer is PSR-2 + some more tweaks.

Why don't you like this? Imo some style checker should be available in a special configuration to keep diffs small and readable

Best, Oskar

**Comment by casperbakker** [comment]
I like the idea of a uniform style that can be easily checked by other contributors, but there are not a lot of contributions to this package and the code is relatively compact.

I like (and use) PSR-2 as well, but in all our projects we explicitly use spaces around modifiers and dots for example. That is the main thing that is changed in this PR :)

Also I do not like to add extra dependencies to composer that only a few people (the developers of this package) need.

**Comment by OskarStark** [comment]
> I like (and use) PSR-2 as well, but in all our projects we explicitly use spaces around modifiers and dots for example. That is the main thing that is changed in this PR :)

This could explicitely be configured then ;-)

> Also I do not like to add extra dependencies to composer that only a few people (the developers of this package) need.

ok, fine, but thats exactly for what the `require-dev` should be used, otherwise this should be removed too https://github.com/picqer/php-barcode-generator/blob/master/composer.json#L23 and should be installed globally on the dev machine :)

But anyway, thank you for your feedback, I'm totally fine with it

**Comment by casperbakker** [comment]
> ok, fine, but thats exactly for what the require-dev should be used, otherwise this should be removed too https://github.com/picqer/php-barcode-generator/blob/master/composer.json#L23 and should be installed globally on the dev machine :)

I know :) I just want it to be as small as possible.

I feel sorry to let you down with this, I just think it has too many downsides for too few upsides in the long run to make this package more complex then it needs to be.

Thank you for your effort nonetheless.

**Pull request closed without merging**
